# Site settings
author: Samuel Tong
title: A Software Dev's Beginning
header-img: img/home-bg.png
email: ssamt1142@gmail.com
copyright_name: Samuel Tong
description: > # this means to ignore newlines until "baseurl:"
  The Start of Something New
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mast1142

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
